language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - 0.7
  - 1.0
script:
  - julia -e 'VERSION >= v"1.0.0" && using Pkg; Pkg.add(".")'
  - julia -e 'VERSION >= v"1.0.0" && using Pkg; Pkg.test("Coils")' 
